spring:
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
          minPartitionCount: 2
      bindings:
        consume-in-0:
          destination: partitioned.destination
          group: consumersGroup