server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
        source-out-0:
          destination: data-topic
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 2
        receive-in-0:
          destination: data-topic
      function:
        definition: receive