server:
  port: 8081

spring:
  cloud:
    stream:
      function:
        definition: receive
      bindings:
        source-out-0:
          destination: sensor-2
        receive-in-0:
          destination: sensor-2

#spring:
#cloud:
#stream:
#bindings:
#source-out-0:
#destination: partitioned.destination
#producer:
#partition-key-expression: headers['partitionKey']
#partition-count: 2